### model
model_name_or_path: /root/model/deepseek-ai/DeepSeek-V2-Lite-Chat
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
deepspeed: /root/Code/360-LLaMA-Factory/examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2

### dataset
dataset: identity
dataset_dir: /root/Code/360-LLaMA-Factory/data
template: deepseek3
cutoff_len: 2048
max_samples: 1000
sequence_parallel_size: 1
sequence_parallel_mode: ulysses  # ulysses zigzag-ring
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 4

### output
output_dir: saves/deepseek/lora/sft
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: tensorboard

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
